### ISSUE TITLE
B9 PartSwitch issue

### ISSUE THREAD

**Issue by aihaw** [JadeOfMaar/RationalResources#6]
Hi!
I seem to have an issue with both the fuelCell the FuelCellArray with B9 as it seems to not have established the FuelSelect module.
I took a look, and being not really a ease with programming, I tried to read some CRP code and had figured humbly that it may need kerbalism to work...
And I don't want to have it, as it conflicts with MKS (mod which brings my personal main goal).
Il have CRP installed and running fine! Thanks by advance can't wait to colonize JNSQ!

**Comment by JadeOfMaar** [comment]
Hi there. I guess MKS changes the way the fuel cells work. I don't use MKS so I'm not aware (by default) that a conflict would happen there. You can delete GameData/RationalResourcesParts/CRP/FuelCells.cfg since you don't want RR to change how they work. And this will cure your issue.

I can't properly write ISRU configs for Kerbalism so no such configs exist or are in a release-ready state.

**Comment by aihaw** [comment]
Ok thank you for the quick answer!
Modulemanager warned me about 6 errors regarding the ore tank CRP config file!
[ModuleManager.log](https://github.com/JadeOfMaar/RationalResources/files/4543090/ModuleManager.log)
